project:
  type: website
  output-dir: docs
  resources:
    - images/
    - logos/

website:
  title: "Anirban Ray"
  site-url: https://rayanirban.github.io
  repo-url: https://github.com/rayanirban/rayanirban.github.io
  favicon: profile.jpg
  open-graph:
    site-name: "Anirban Ray"
    title: "Anirban Ray"
    description: "PhD Student in Computer Science at Technische Universität Dresden & Human Technopole, Italy. Research focuses on flow-matching models for biological image restoration."
  twitter-card:
    site: "@anirbanray_"
    creator: "@anirbanray_"
  page-footer:
    center: "© 2025 Your Name. All rights reserved."
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd

format:
  html:
    theme: none
    css: styles.css
    toc: false
